/**
 * @fileoverview gRPC-Web generated client stub for yeying.api.certificate
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: yeying/api/certificate/certificate.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as yeying_api_certificate_certificate_pb from '../../../yeying/api/certificate/certificate_pb'; // proto import: "yeying/api/certificate/certificate.proto"


export class CertificateClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSign = new grpcWeb.MethodDescriptor(
    '/yeying.api.certificate.Certificate/Sign',
    grpcWeb.MethodType.UNARY,
    yeying_api_certificate_certificate_pb.SignRequest,
    yeying_api_certificate_certificate_pb.SignResponse,
    (request: yeying_api_certificate_certificate_pb.SignRequest) => {
      return request.serializeBinary();
    },
    yeying_api_certificate_certificate_pb.SignResponse.deserializeBinary
  );

  sign(
    request: yeying_api_certificate_certificate_pb.SignRequest,
    metadata?: grpcWeb.Metadata | null): Promise<yeying_api_certificate_certificate_pb.SignResponse>;

  sign(
    request: yeying_api_certificate_certificate_pb.SignRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: yeying_api_certificate_certificate_pb.SignResponse) => void): grpcWeb.ClientReadableStream<yeying_api_certificate_certificate_pb.SignResponse>;

  sign(
    request: yeying_api_certificate_certificate_pb.SignRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: yeying_api_certificate_certificate_pb.SignResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/yeying.api.certificate.Certificate/Sign',
        request,
        metadata || {},
        this.methodDescriptorSign,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/yeying.api.certificate.Certificate/Sign',
    request,
    metadata || {},
    this.methodDescriptorSign);
  }

  methodDescriptorGet = new grpcWeb.MethodDescriptor(
    '/yeying.api.certificate.Certificate/Get',
    grpcWeb.MethodType.UNARY,
    yeying_api_certificate_certificate_pb.GetRequest,
    yeying_api_certificate_certificate_pb.GetResponse,
    (request: yeying_api_certificate_certificate_pb.GetRequest) => {
      return request.serializeBinary();
    },
    yeying_api_certificate_certificate_pb.GetResponse.deserializeBinary
  );

  get(
    request: yeying_api_certificate_certificate_pb.GetRequest,
    metadata?: grpcWeb.Metadata | null): Promise<yeying_api_certificate_certificate_pb.GetResponse>;

  get(
    request: yeying_api_certificate_certificate_pb.GetRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: yeying_api_certificate_certificate_pb.GetResponse) => void): grpcWeb.ClientReadableStream<yeying_api_certificate_certificate_pb.GetResponse>;

  get(
    request: yeying_api_certificate_certificate_pb.GetRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: yeying_api_certificate_certificate_pb.GetResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/yeying.api.certificate.Certificate/Get',
        request,
        metadata || {},
        this.methodDescriptorGet,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/yeying.api.certificate.Certificate/Get',
    request,
    metadata || {},
    this.methodDescriptorGet);
  }

}

