// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file yeying/api/apps/zuoyepigai/archive.proto (package yeying.api.apps.zuoyepigai, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { MessageHeader, ResponseStatus } from "../../common/message_pb";
import { file_yeying_api_common_message } from "../../common/message_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file yeying/api/apps/zuoyepigai/archive.proto.
 */
export const file_yeying_api_apps_zuoyepigai_archive: GenFile = /*@__PURE__*/
  fileDesc("Cih5ZXlpbmcvYXBpL2FwcHMvenVveWVwaWdhaS9hcmNoaXZlLnByb3RvEhp5ZXlpbmcuYXBpLmFwcHMuenVveWVwaWdhaSKIAQoSQXJjaGl2ZUxpc3RSZXF1ZXN0EjAKBmhlYWRlchgBIAEoCzIgLnlleWluZy5hcGkuY29tbW9uLk1lc3NhZ2VIZWFkZXISQAoEYm9keRgCIAEoCzIyLnlleWluZy5hcGkuYXBwcy56dW95ZXBpZ2FpLkFyY2hpdmVMaXN0UmVxdWVzdEJvZHkiKQoWQXJjaGl2ZUxpc3RSZXF1ZXN0Qm9keRIPCgd1c2VyVWlkGAEgASgJIlgKE0FyY2hpdmVMaXN0UmVzcG9uc2USQQoEYm9keRgBIAEoCzIzLnlleWluZy5hcGkuYXBwcy56dW95ZXBpZ2FpLkFyY2hpdmVMaXN0UmVzcG9uc2VCb2R5IoMBChdBcmNoaXZlTGlzdFJlc3BvbnNlQm9keRIxCgZzdGF0dXMYASABKAsyIS55ZXlpbmcuYXBpLmNvbW1vbi5SZXNwb25zZVN0YXR1cxI1CgRsaXN0GAIgAygLMicueWV5aW5nLmFwaS5hcHBzLnp1b3llcGlnYWkuQXJjaGl2ZU1ldGEihgEKC0FyY2hpdmVNZXRhEgsKA3VJZBgBIAEoCRIMCgRuYW1lGAIgASgJEhIKCnRlYWNoZXJVaWQYAyABKAkSDwoHc3ViamVjdBgEIAEoCRIRCgljcmVhdGVkQXQYBSABKAMSEQoJdXBkYXRlZEF0GAYgASgDEhEKCWlzRGVsZXRlZBgHIAEoCCKMAQoUQXJjaGl2ZURldGFpbFJlcXVlc3QSMAoGaGVhZGVyGAEgASgLMiAueWV5aW5nLmFwaS5jb21tb24uTWVzc2FnZUhlYWRlchJCCgRib2R5GAIgASgLMjQueWV5aW5nLmFwaS5hcHBzLnp1b3llcGlnYWkuQXJjaGl2ZURldGFpbFJlcXVlc3RCb2R5IicKGEFyY2hpdmVEZXRhaWxSZXF1ZXN0Qm9keRILCgN1aWQYASABKAkiXAoVQXJjaGl2ZURldGFpbFJlc3BvbnNlEkMKBGJvZHkYASABKAsyNS55ZXlpbmcuYXBpLmFwcHMuenVveWVwaWdhaS5BcmNoaXZlRGV0YWlsUmVzcG9uc2VCb2R5IoUBChlBcmNoaXZlRGV0YWlsUmVzcG9uc2VCb2R5EjEKBnN0YXR1cxgBIAEoCzIhLnlleWluZy5hcGkuY29tbW9uLlJlc3BvbnNlU3RhdHVzEjUKBG1ldGEYAiABKAsyJy55ZXlpbmcuYXBpLmFwcHMuenVveWVwaWdhaS5BcmNoaXZlTWV0YTLlAQoHQXJjaGl2ZRJpCgRMaXN0Ei4ueWV5aW5nLmFwaS5hcHBzLnp1b3llcGlnYWkuQXJjaGl2ZUxpc3RSZXF1ZXN0Gi8ueWV5aW5nLmFwaS5hcHBzLnp1b3llcGlnYWkuQXJjaGl2ZUxpc3RSZXNwb25zZSIAEm8KBkRldGFpbBIwLnlleWluZy5hcGkuYXBwcy56dW95ZXBpZ2FpLkFyY2hpdmVEZXRhaWxSZXF1ZXN0GjEueWV5aW5nLmFwaS5hcHBzLnp1b3llcGlnYWkuQXJjaGl2ZURldGFpbFJlc3BvbnNlIgBCHFoaeWV5aW5nL2FwaS9hcHBzL3p1b3llcGlnYWliBnByb3RvMw", [file_yeying_api_common_message]);

/**
 * 列表
 *
 * @generated from message yeying.api.apps.zuoyepigai.ArchiveListRequest
 */
export type ArchiveListRequest = Message<"yeying.api.apps.zuoyepigai.ArchiveListRequest"> & {
  /**
   * @generated from field: yeying.api.common.MessageHeader header = 1;
   */
  header?: MessageHeader;

  /**
   * @generated from field: yeying.api.apps.zuoyepigai.ArchiveListRequestBody body = 2;
   */
  body?: ArchiveListRequestBody;
};

/**
 * Describes the message yeying.api.apps.zuoyepigai.ArchiveListRequest.
 * Use `create(ArchiveListRequestSchema)` to create a new message.
 */
export const ArchiveListRequestSchema: GenMessage<ArchiveListRequest> = /*@__PURE__*/
  messageDesc(file_yeying_api_apps_zuoyepigai_archive, 0);

/**
 * @generated from message yeying.api.apps.zuoyepigai.ArchiveListRequestBody
 */
export type ArchiveListRequestBody = Message<"yeying.api.apps.zuoyepigai.ArchiveListRequestBody"> & {
  /**
   * @generated from field: string userUid = 1;
   */
  userUid: string;
};

/**
 * Describes the message yeying.api.apps.zuoyepigai.ArchiveListRequestBody.
 * Use `create(ArchiveListRequestBodySchema)` to create a new message.
 */
export const ArchiveListRequestBodySchema: GenMessage<ArchiveListRequestBody> = /*@__PURE__*/
  messageDesc(file_yeying_api_apps_zuoyepigai_archive, 1);

/**
 * @generated from message yeying.api.apps.zuoyepigai.ArchiveListResponse
 */
export type ArchiveListResponse = Message<"yeying.api.apps.zuoyepigai.ArchiveListResponse"> & {
  /**
   * @generated from field: yeying.api.apps.zuoyepigai.ArchiveListResponseBody body = 1;
   */
  body?: ArchiveListResponseBody;
};

/**
 * Describes the message yeying.api.apps.zuoyepigai.ArchiveListResponse.
 * Use `create(ArchiveListResponseSchema)` to create a new message.
 */
export const ArchiveListResponseSchema: GenMessage<ArchiveListResponse> = /*@__PURE__*/
  messageDesc(file_yeying_api_apps_zuoyepigai_archive, 2);

/**
 * @generated from message yeying.api.apps.zuoyepigai.ArchiveListResponseBody
 */
export type ArchiveListResponseBody = Message<"yeying.api.apps.zuoyepigai.ArchiveListResponseBody"> & {
  /**
   * @generated from field: yeying.api.common.ResponseStatus status = 1;
   */
  status?: ResponseStatus;

  /**
   * repeated 表示 List
   *
   * @generated from field: repeated yeying.api.apps.zuoyepigai.ArchiveMeta list = 2;
   */
  list: ArchiveMeta[];
};

/**
 * Describes the message yeying.api.apps.zuoyepigai.ArchiveListResponseBody.
 * Use `create(ArchiveListResponseBodySchema)` to create a new message.
 */
export const ArchiveListResponseBodySchema: GenMessage<ArchiveListResponseBody> = /*@__PURE__*/
  messageDesc(file_yeying_api_apps_zuoyepigai_archive, 3);

/**
 * @generated from message yeying.api.apps.zuoyepigai.ArchiveMeta
 */
export type ArchiveMeta = Message<"yeying.api.apps.zuoyepigai.ArchiveMeta"> & {
  /**
   * 主键标识ID
   *
   * @generated from field: string uId = 1;
   */
  uId: string;

  /**
   * 档案名称
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * 老师Uid
   *
   * @generated from field: string teacherUid = 3;
   */
  teacherUid: string;

  /**
   * 科目
   *
   * @generated from field: string subject = 4;
   */
  subject: string;

  /**
   * 创建时间
   *
   * @generated from field: int64 createdAt = 5;
   */
  createdAt: bigint;

  /**
   * 修改时间
   *
   * @generated from field: int64 updatedAt = 6;
   */
  updatedAt: bigint;

  /**
   * 是否删除
   *
   * @generated from field: bool isDeleted = 7;
   */
  isDeleted: boolean;
};

/**
 * Describes the message yeying.api.apps.zuoyepigai.ArchiveMeta.
 * Use `create(ArchiveMetaSchema)` to create a new message.
 */
export const ArchiveMetaSchema: GenMessage<ArchiveMeta> = /*@__PURE__*/
  messageDesc(file_yeying_api_apps_zuoyepigai_archive, 4);

/**
 * 详情
 *
 * @generated from message yeying.api.apps.zuoyepigai.ArchiveDetailRequest
 */
export type ArchiveDetailRequest = Message<"yeying.api.apps.zuoyepigai.ArchiveDetailRequest"> & {
  /**
   * @generated from field: yeying.api.common.MessageHeader header = 1;
   */
  header?: MessageHeader;

  /**
   * @generated from field: yeying.api.apps.zuoyepigai.ArchiveDetailRequestBody body = 2;
   */
  body?: ArchiveDetailRequestBody;
};

/**
 * Describes the message yeying.api.apps.zuoyepigai.ArchiveDetailRequest.
 * Use `create(ArchiveDetailRequestSchema)` to create a new message.
 */
export const ArchiveDetailRequestSchema: GenMessage<ArchiveDetailRequest> = /*@__PURE__*/
  messageDesc(file_yeying_api_apps_zuoyepigai_archive, 5);

/**
 * @generated from message yeying.api.apps.zuoyepigai.ArchiveDetailRequestBody
 */
export type ArchiveDetailRequestBody = Message<"yeying.api.apps.zuoyepigai.ArchiveDetailRequestBody"> & {
  /**
   * @generated from field: string uid = 1;
   */
  uid: string;
};

/**
 * Describes the message yeying.api.apps.zuoyepigai.ArchiveDetailRequestBody.
 * Use `create(ArchiveDetailRequestBodySchema)` to create a new message.
 */
export const ArchiveDetailRequestBodySchema: GenMessage<ArchiveDetailRequestBody> = /*@__PURE__*/
  messageDesc(file_yeying_api_apps_zuoyepigai_archive, 6);

/**
 * @generated from message yeying.api.apps.zuoyepigai.ArchiveDetailResponse
 */
export type ArchiveDetailResponse = Message<"yeying.api.apps.zuoyepigai.ArchiveDetailResponse"> & {
  /**
   * @generated from field: yeying.api.apps.zuoyepigai.ArchiveDetailResponseBody body = 1;
   */
  body?: ArchiveDetailResponseBody;
};

/**
 * Describes the message yeying.api.apps.zuoyepigai.ArchiveDetailResponse.
 * Use `create(ArchiveDetailResponseSchema)` to create a new message.
 */
export const ArchiveDetailResponseSchema: GenMessage<ArchiveDetailResponse> = /*@__PURE__*/
  messageDesc(file_yeying_api_apps_zuoyepigai_archive, 7);

/**
 * @generated from message yeying.api.apps.zuoyepigai.ArchiveDetailResponseBody
 */
export type ArchiveDetailResponseBody = Message<"yeying.api.apps.zuoyepigai.ArchiveDetailResponseBody"> & {
  /**
   * @generated from field: yeying.api.common.ResponseStatus status = 1;
   */
  status?: ResponseStatus;

  /**
   * @generated from field: yeying.api.apps.zuoyepigai.ArchiveMeta meta = 2;
   */
  meta?: ArchiveMeta;
};

/**
 * Describes the message yeying.api.apps.zuoyepigai.ArchiveDetailResponseBody.
 * Use `create(ArchiveDetailResponseBodySchema)` to create a new message.
 */
export const ArchiveDetailResponseBodySchema: GenMessage<ArchiveDetailResponseBody> = /*@__PURE__*/
  messageDesc(file_yeying_api_apps_zuoyepigai_archive, 8);

/**
 * *
 * 档案管理
 *
 * @generated from service yeying.api.apps.zuoyepigai.Archive
 */
export const Archive: GenService<{
  /**
   * 列表
   *
   * @generated from rpc yeying.api.apps.zuoyepigai.Archive.List
   */
  list: {
    methodKind: "unary";
    input: typeof ArchiveListRequestSchema;
    output: typeof ArchiveListResponseSchema;
  },
  /**
   * 详情
   *
   * @generated from rpc yeying.api.apps.zuoyepigai.Archive.Detail
   */
  detail: {
    methodKind: "unary";
    input: typeof ArchiveDetailRequestSchema;
    output: typeof ArchiveDetailResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_yeying_api_apps_zuoyepigai_archive, 0);

