/**
 * @fileoverview gRPC-Web generated client stub for yeying.api.event
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: yeying/api/event/event.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as yeying_api_event_event_pb from '../../../yeying/api/event/event_pb'; // proto import: "yeying/api/event/event.proto"


export class EventClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorProduce = new grpcWeb.MethodDescriptor(
    '/yeying.api.event.Event/Produce',
    grpcWeb.MethodType.UNARY,
    yeying_api_event_event_pb.ProduceRequest,
    yeying_api_event_event_pb.ProduceResponse,
    (request: yeying_api_event_event_pb.ProduceRequest) => {
      return request.serializeBinary();
    },
    yeying_api_event_event_pb.ProduceResponse.deserializeBinary
  );

  produce(
    request: yeying_api_event_event_pb.ProduceRequest,
    metadata?: grpcWeb.Metadata | null): Promise<yeying_api_event_event_pb.ProduceResponse>;

  produce(
    request: yeying_api_event_event_pb.ProduceRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: yeying_api_event_event_pb.ProduceResponse) => void): grpcWeb.ClientReadableStream<yeying_api_event_event_pb.ProduceResponse>;

  produce(
    request: yeying_api_event_event_pb.ProduceRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: yeying_api_event_event_pb.ProduceResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/yeying.api.event.Event/Produce',
        request,
        metadata || {},
        this.methodDescriptorProduce,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/yeying.api.event.Event/Produce',
    request,
    metadata || {},
    this.methodDescriptorProduce);
  }

  methodDescriptorConsume = new grpcWeb.MethodDescriptor(
    '/yeying.api.event.Event/Consume',
    grpcWeb.MethodType.UNARY,
    yeying_api_event_event_pb.ConsumeRequest,
    yeying_api_event_event_pb.ConsumeResponse,
    (request: yeying_api_event_event_pb.ConsumeRequest) => {
      return request.serializeBinary();
    },
    yeying_api_event_event_pb.ConsumeResponse.deserializeBinary
  );

  consume(
    request: yeying_api_event_event_pb.ConsumeRequest,
    metadata?: grpcWeb.Metadata | null): Promise<yeying_api_event_event_pb.ConsumeResponse>;

  consume(
    request: yeying_api_event_event_pb.ConsumeRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: yeying_api_event_event_pb.ConsumeResponse) => void): grpcWeb.ClientReadableStream<yeying_api_event_event_pb.ConsumeResponse>;

  consume(
    request: yeying_api_event_event_pb.ConsumeRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: yeying_api_event_event_pb.ConsumeResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/yeying.api.event.Event/Consume',
        request,
        metadata || {},
        this.methodDescriptorConsume,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/yeying.api.event.Event/Consume',
    request,
    metadata || {},
    this.methodDescriptorConsume);
  }

}

