/**
 * @fileoverview gRPC-Web generated client stub for yeying.api.service
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v4.25.0
// source: yeying/api/service/service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var yeying_api_common_message_pb = require('../../../yeying/api/common/message_pb.cjs')

var yeying_api_common_code_pb = require('../../../yeying/api/common/code_pb.cjs')
const proto = {};
proto.yeying = {};
proto.yeying.api = {};
proto.yeying.api.service = require('./service_pb.cjs');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.yeying.api.service.ServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.yeying.api.service.ServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.yeying.api.service.WhoamiRequest,
 *   !proto.yeying.api.service.WhoamiResponse>}
 */
const methodDescriptor_Service_Whoami = new grpc.web.MethodDescriptor(
  '/yeying.api.service.Service/Whoami',
  grpc.web.MethodType.UNARY,
  proto.yeying.api.service.WhoamiRequest,
  proto.yeying.api.service.WhoamiResponse,
  /**
   * @param {!proto.yeying.api.service.WhoamiRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.yeying.api.service.WhoamiResponse.deserializeBinary
);


/**
 * @param {!proto.yeying.api.service.WhoamiRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.yeying.api.service.WhoamiResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.yeying.api.service.WhoamiResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.yeying.api.service.ServiceClient.prototype.whoami =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/yeying.api.service.Service/Whoami',
      request,
      metadata || {},
      methodDescriptor_Service_Whoami,
      callback);
};


/**
 * @param {!proto.yeying.api.service.WhoamiRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.yeying.api.service.WhoamiResponse>}
 *     Promise that resolves to the response
 */
proto.yeying.api.service.ServicePromiseClient.prototype.whoami =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/yeying.api.service.Service/Whoami',
      request,
      metadata || {},
      methodDescriptor_Service_Whoami);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.yeying.api.service.RegisterRequest,
 *   !proto.yeying.api.service.RegisterResponse>}
 */
const methodDescriptor_Service_Register = new grpc.web.MethodDescriptor(
  '/yeying.api.service.Service/Register',
  grpc.web.MethodType.UNARY,
  proto.yeying.api.service.RegisterRequest,
  proto.yeying.api.service.RegisterResponse,
  /**
   * @param {!proto.yeying.api.service.RegisterRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.yeying.api.service.RegisterResponse.deserializeBinary
);


/**
 * @param {!proto.yeying.api.service.RegisterRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.yeying.api.service.RegisterResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.yeying.api.service.RegisterResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.yeying.api.service.ServiceClient.prototype.register =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/yeying.api.service.Service/Register',
      request,
      metadata || {},
      methodDescriptor_Service_Register,
      callback);
};


/**
 * @param {!proto.yeying.api.service.RegisterRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.yeying.api.service.RegisterResponse>}
 *     Promise that resolves to the response
 */
proto.yeying.api.service.ServicePromiseClient.prototype.register =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/yeying.api.service.Service/Register',
      request,
      metadata || {},
      methodDescriptor_Service_Register);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.yeying.api.service.SearchRequest,
 *   !proto.yeying.api.service.SearchResponse>}
 */
const methodDescriptor_Service_Search = new grpc.web.MethodDescriptor(
  '/yeying.api.service.Service/Search',
  grpc.web.MethodType.UNARY,
  proto.yeying.api.service.SearchRequest,
  proto.yeying.api.service.SearchResponse,
  /**
   * @param {!proto.yeying.api.service.SearchRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.yeying.api.service.SearchResponse.deserializeBinary
);


/**
 * @param {!proto.yeying.api.service.SearchRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.yeying.api.service.SearchResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.yeying.api.service.SearchResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.yeying.api.service.ServiceClient.prototype.search =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/yeying.api.service.Service/Search',
      request,
      metadata || {},
      methodDescriptor_Service_Search,
      callback);
};


/**
 * @param {!proto.yeying.api.service.SearchRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.yeying.api.service.SearchResponse>}
 *     Promise that resolves to the response
 */
proto.yeying.api.service.ServicePromiseClient.prototype.search =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/yeying.api.service.Service/Search',
      request,
      metadata || {},
      methodDescriptor_Service_Search);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.yeying.api.service.UnregisterRequest,
 *   !proto.yeying.api.service.UnregisterResponse>}
 */
const methodDescriptor_Service_Unregister = new grpc.web.MethodDescriptor(
  '/yeying.api.service.Service/Unregister',
  grpc.web.MethodType.UNARY,
  proto.yeying.api.service.UnregisterRequest,
  proto.yeying.api.service.UnregisterResponse,
  /**
   * @param {!proto.yeying.api.service.UnregisterRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.yeying.api.service.UnregisterResponse.deserializeBinary
);


/**
 * @param {!proto.yeying.api.service.UnregisterRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.yeying.api.service.UnregisterResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.yeying.api.service.UnregisterResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.yeying.api.service.ServiceClient.prototype.unregister =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/yeying.api.service.Service/Unregister',
      request,
      metadata || {},
      methodDescriptor_Service_Unregister,
      callback);
};


/**
 * @param {!proto.yeying.api.service.UnregisterRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.yeying.api.service.UnregisterResponse>}
 *     Promise that resolves to the response
 */
proto.yeying.api.service.ServicePromiseClient.prototype.unregister =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/yeying.api.service.Service/Unregister',
      request,
      metadata || {},
      methodDescriptor_Service_Unregister);
};


module.exports = proto.yeying.api.service;

