// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file yeying/api/invitation/invitation.proto (package yeying.api.invitation, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { MessageHeader, ResponseStatus } from "../common/message_pb";
import { file_yeying_api_common_message } from "../common/message_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file yeying/api/invitation/invitation.proto.
 */
export const file_yeying_api_invitation_invitation: GenFile = /*@__PURE__*/
  fileDesc("CiZ5ZXlpbmcvYXBpL2ludml0YXRpb24vaW52aXRhdGlvbi5wcm90bxIVeWV5aW5nLmFwaS5pbnZpdGF0aW9uIsIBChJJbnZpdGF0aW9uTWV0YWRhdGESOQoFc2NlbmUYASABKA4yKi55ZXlpbmcuYXBpLmludml0YXRpb24uSW52aXRhdGlvblNjZW5lRW51bRIMCgRjb2RlGAIgASgJEg8KB2NyZWF0ZWQYAyABKAkSDwoHZXhwaXJlZBgEIAEoCRIMCgR1c2VkGAUgASgJEg8KB2ludml0ZXIYBiABKAkSDwoHaW52aXRlZRgHIAEoCRIRCglzaWduYXR1cmUYCCABKAkifQoPR2VuZXJhdGVSZXF1ZXN0EjAKBmhlYWRlchgBIAEoCzIgLnlleWluZy5hcGkuY29tbW9uLk1lc3NhZ2VIZWFkZXISOAoEYm9keRgCIAEoCzIqLnlleWluZy5hcGkuaW52aXRhdGlvbi5HZW5lcmF0ZVJlcXVlc3RCb2R5Il8KE0dlbmVyYXRlUmVxdWVzdEJvZHkSOQoFc2NlbmUYASABKA4yKi55ZXlpbmcuYXBpLmludml0YXRpb24uSW52aXRhdGlvblNjZW5lRW51bRINCgVjb3VudBgCIAEoDSJ5Cg1WZXJpZnlSZXF1ZXN0EjAKBmhlYWRlchgBIAEoCzIgLnlleWluZy5hcGkuY29tbW9uLk1lc3NhZ2VIZWFkZXISNgoEYm9keRgCIAEoCzIoLnlleWluZy5hcGkuaW52aXRhdGlvbi5WZXJpZnlSZXF1ZXN0Qm9keSIhChFWZXJpZnlSZXF1ZXN0Qm9keRIMCgRjb2RlGAEgASgJInsKDlZlcmlmeVJlc3BvbnNlEjAKBmhlYWRlchgBIAEoCzIgLnlleWluZy5hcGkuY29tbW9uLk1lc3NhZ2VIZWFkZXISNwoEYm9keRgCIAEoCzIpLnlleWluZy5hcGkuaW52aXRhdGlvbi5WZXJpZnlSZXNwb25zZUJvZHkiRwoSVmVyaWZ5UmVzcG9uc2VCb2R5EjEKBnN0YXR1cxgBIAEoCzIhLnlleWluZy5hcGkuY29tbW9uLlJlc3BvbnNlU3RhdHVzIn8KEEdlbmVyYXRlUmVzcG9uc2USMAoGaGVhZGVyGAEgASgLMiAueWV5aW5nLmFwaS5jb21tb24uTWVzc2FnZUhlYWRlchI5CgRib2R5GAIgASgLMisueWV5aW5nLmFwaS5pbnZpdGF0aW9uLkdlbmVyYXRlUmVzcG9uc2VCb2R5IokBChRHZW5lcmF0ZVJlc3BvbnNlQm9keRIxCgZzdGF0dXMYASABKAsyIS55ZXlpbmcuYXBpLmNvbW1vbi5SZXNwb25zZVN0YXR1cxI+CgtpbnZpdGF0aW9ucxgCIAMoCzIpLnlleWluZy5hcGkuaW52aXRhdGlvbi5JbnZpdGF0aW9uTWV0YWRhdGEqTgoTSW52aXRhdGlvblNjZW5lRW51bRIcChhJTlZJVEFUSU9OX1NDRU5FX1VOS05PV04QABIZChVJTlZJVEFUSU9OX1NDRU5FX1VTRVIQATLEAQoKSW52aXRhdGlvbhJdCghHZW5lcmF0ZRImLnlleWluZy5hcGkuaW52aXRhdGlvbi5HZW5lcmF0ZVJlcXVlc3QaJy55ZXlpbmcuYXBpLmludml0YXRpb24uR2VuZXJhdGVSZXNwb25zZSIAElcKBlZlcmlmeRIkLnlleWluZy5hcGkuaW52aXRhdGlvbi5WZXJpZnlSZXF1ZXN0GiUueWV5aW5nLmFwaS5pbnZpdGF0aW9uLlZlcmlmeVJlc3BvbnNlIgBCF1oVeWV5aW5nL2FwaS9pbnZpdGF0aW9uYgZwcm90bzM", [file_yeying_api_common_message]);

/**
 * @generated from message yeying.api.invitation.InvitationMetadata
 */
export type InvitationMetadata = Message<"yeying.api.invitation.InvitationMetadata"> & {
  /**
   * 使用场景 
   *
   * @generated from field: yeying.api.invitation.InvitationSceneEnum scene = 1;
   */
  scene: InvitationSceneEnum;

  /**
   * 邀请码 
   *
   * @generated from field: string code = 2;
   */
  code: string;

  /**
   * 创建时间 
   *
   * @generated from field: string created = 3;
   */
  created: string;

  /**
   * 有效截止日期 
   *
   * @generated from field: string expired = 4;
   */
  expired: string;

  /**
   * 使用时间 
   *
   * @generated from field: string used = 5;
   */
  used: string;

  /**
   * 邀请者
   *
   * @generated from field: string inviter = 6;
   */
  inviter: string;

  /**
   * 受邀者
   *
   * @generated from field: string invitee = 7;
   */
  invitee: string;

  /**
   * 邀请者签名
   *
   * @generated from field: string signature = 8;
   */
  signature: string;
};

/**
 * Describes the message yeying.api.invitation.InvitationMetadata.
 * Use `create(InvitationMetadataSchema)` to create a new message.
 */
export const InvitationMetadataSchema: GenMessage<InvitationMetadata> = /*@__PURE__*/
  messageDesc(file_yeying_api_invitation_invitation, 0);

/**
 * @generated from message yeying.api.invitation.GenerateRequest
 */
export type GenerateRequest = Message<"yeying.api.invitation.GenerateRequest"> & {
  /**
   * @generated from field: yeying.api.common.MessageHeader header = 1;
   */
  header?: MessageHeader;

  /**
   * @generated from field: yeying.api.invitation.GenerateRequestBody body = 2;
   */
  body?: GenerateRequestBody;
};

/**
 * Describes the message yeying.api.invitation.GenerateRequest.
 * Use `create(GenerateRequestSchema)` to create a new message.
 */
export const GenerateRequestSchema: GenMessage<GenerateRequest> = /*@__PURE__*/
  messageDesc(file_yeying_api_invitation_invitation, 1);

/**
 * @generated from message yeying.api.invitation.GenerateRequestBody
 */
export type GenerateRequestBody = Message<"yeying.api.invitation.GenerateRequestBody"> & {
  /**
   * @generated from field: yeying.api.invitation.InvitationSceneEnum scene = 1;
   */
  scene: InvitationSceneEnum;

  /**
   * @generated from field: uint32 count = 2;
   */
  count: number;
};

/**
 * Describes the message yeying.api.invitation.GenerateRequestBody.
 * Use `create(GenerateRequestBodySchema)` to create a new message.
 */
export const GenerateRequestBodySchema: GenMessage<GenerateRequestBody> = /*@__PURE__*/
  messageDesc(file_yeying_api_invitation_invitation, 2);

/**
 * @generated from message yeying.api.invitation.VerifyRequest
 */
export type VerifyRequest = Message<"yeying.api.invitation.VerifyRequest"> & {
  /**
   * @generated from field: yeying.api.common.MessageHeader header = 1;
   */
  header?: MessageHeader;

  /**
   * @generated from field: yeying.api.invitation.VerifyRequestBody body = 2;
   */
  body?: VerifyRequestBody;
};

/**
 * Describes the message yeying.api.invitation.VerifyRequest.
 * Use `create(VerifyRequestSchema)` to create a new message.
 */
export const VerifyRequestSchema: GenMessage<VerifyRequest> = /*@__PURE__*/
  messageDesc(file_yeying_api_invitation_invitation, 3);

/**
 * @generated from message yeying.api.invitation.VerifyRequestBody
 */
export type VerifyRequestBody = Message<"yeying.api.invitation.VerifyRequestBody"> & {
  /**
   * @generated from field: string code = 1;
   */
  code: string;
};

/**
 * Describes the message yeying.api.invitation.VerifyRequestBody.
 * Use `create(VerifyRequestBodySchema)` to create a new message.
 */
export const VerifyRequestBodySchema: GenMessage<VerifyRequestBody> = /*@__PURE__*/
  messageDesc(file_yeying_api_invitation_invitation, 4);

/**
 * @generated from message yeying.api.invitation.VerifyResponse
 */
export type VerifyResponse = Message<"yeying.api.invitation.VerifyResponse"> & {
  /**
   * @generated from field: yeying.api.common.MessageHeader header = 1;
   */
  header?: MessageHeader;

  /**
   * @generated from field: yeying.api.invitation.VerifyResponseBody body = 2;
   */
  body?: VerifyResponseBody;
};

/**
 * Describes the message yeying.api.invitation.VerifyResponse.
 * Use `create(VerifyResponseSchema)` to create a new message.
 */
export const VerifyResponseSchema: GenMessage<VerifyResponse> = /*@__PURE__*/
  messageDesc(file_yeying_api_invitation_invitation, 5);

/**
 * @generated from message yeying.api.invitation.VerifyResponseBody
 */
export type VerifyResponseBody = Message<"yeying.api.invitation.VerifyResponseBody"> & {
  /**
   * @generated from field: yeying.api.common.ResponseStatus status = 1;
   */
  status?: ResponseStatus;
};

/**
 * Describes the message yeying.api.invitation.VerifyResponseBody.
 * Use `create(VerifyResponseBodySchema)` to create a new message.
 */
export const VerifyResponseBodySchema: GenMessage<VerifyResponseBody> = /*@__PURE__*/
  messageDesc(file_yeying_api_invitation_invitation, 6);

/**
 * @generated from message yeying.api.invitation.GenerateResponse
 */
export type GenerateResponse = Message<"yeying.api.invitation.GenerateResponse"> & {
  /**
   * @generated from field: yeying.api.common.MessageHeader header = 1;
   */
  header?: MessageHeader;

  /**
   * @generated from field: yeying.api.invitation.GenerateResponseBody body = 2;
   */
  body?: GenerateResponseBody;
};

/**
 * Describes the message yeying.api.invitation.GenerateResponse.
 * Use `create(GenerateResponseSchema)` to create a new message.
 */
export const GenerateResponseSchema: GenMessage<GenerateResponse> = /*@__PURE__*/
  messageDesc(file_yeying_api_invitation_invitation, 7);

/**
 * @generated from message yeying.api.invitation.GenerateResponseBody
 */
export type GenerateResponseBody = Message<"yeying.api.invitation.GenerateResponseBody"> & {
  /**
   * @generated from field: yeying.api.common.ResponseStatus status = 1;
   */
  status?: ResponseStatus;

  /**
   * @generated from field: repeated yeying.api.invitation.InvitationMetadata invitations = 2;
   */
  invitations: InvitationMetadata[];
};

/**
 * Describes the message yeying.api.invitation.GenerateResponseBody.
 * Use `create(GenerateResponseBodySchema)` to create a new message.
 */
export const GenerateResponseBodySchema: GenMessage<GenerateResponseBody> = /*@__PURE__*/
  messageDesc(file_yeying_api_invitation_invitation, 8);

/**
 * @generated from enum yeying.api.invitation.InvitationSceneEnum
 */
export enum InvitationSceneEnum {
  /**
   * 未知编码，是一种占位符
   *
   * @generated from enum value: INVITATION_SCENE_UNKNOWN = 0;
   */
  INVITATION_SCENE_UNKNOWN = 0,

  /**
   * 用户邀请码，成为某个服务的用户，但是这个服务并不开放，只允许受邀使用
   *
   * @generated from enum value: INVITATION_SCENE_USER = 1;
   */
  INVITATION_SCENE_USER = 1,
}

/**
 * Describes the enum yeying.api.invitation.InvitationSceneEnum.
 */
export const InvitationSceneEnumSchema: GenEnum<InvitationSceneEnum> = /*@__PURE__*/
  enumDesc(file_yeying_api_invitation_invitation, 0);

/**
 * @generated from service yeying.api.invitation.Invitation
 */
export const Invitation: GenService<{
  /**
   * 生成邀请码
   *
   * @generated from rpc yeying.api.invitation.Invitation.Generate
   */
  generate: {
    methodKind: "unary";
    input: typeof GenerateRequestSchema;
    output: typeof GenerateResponseSchema;
  },
  /**
   * 验证邀请码
   *
   * @generated from rpc yeying.api.invitation.Invitation.Verify
   */
  verify: {
    methodKind: "unary";
    input: typeof VerifyRequestSchema;
    output: typeof VerifyResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_yeying_api_invitation_invitation, 0);

