/**
 * @fileoverview gRPC-Web generated client stub for yeying.api.invitation
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v4.25.0
// source: yeying/api/invitation/invitation.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var yeying_api_common_message_pb = require('../../../yeying/api/common/message_pb.cjs')
const proto = {};
proto.yeying = {};
proto.yeying.api = {};
proto.yeying.api.invitation = require('./invitation_pb.cjs');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.yeying.api.invitation.InvitationClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.yeying.api.invitation.InvitationPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.yeying.api.invitation.InputRequest,
 *   !proto.yeying.api.invitation.InputResponse>}
 */
const methodDescriptor_Invitation_Input = new grpc.web.MethodDescriptor(
  '/yeying.api.invitation.Invitation/Input',
  grpc.web.MethodType.UNARY,
  proto.yeying.api.invitation.InputRequest,
  proto.yeying.api.invitation.InputResponse,
  /**
   * @param {!proto.yeying.api.invitation.InputRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.yeying.api.invitation.InputResponse.deserializeBinary
);


/**
 * @param {!proto.yeying.api.invitation.InputRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.yeying.api.invitation.InputResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.yeying.api.invitation.InputResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.yeying.api.invitation.InvitationClient.prototype.input =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/yeying.api.invitation.Invitation/Input',
      request,
      metadata || {},
      methodDescriptor_Invitation_Input,
      callback);
};


/**
 * @param {!proto.yeying.api.invitation.InputRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.yeying.api.invitation.InputResponse>}
 *     Promise that resolves to the response
 */
proto.yeying.api.invitation.InvitationPromiseClient.prototype.input =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/yeying.api.invitation.Invitation/Input',
      request,
      metadata || {},
      methodDescriptor_Invitation_Input);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.yeying.api.invitation.GenerateRequest,
 *   !proto.yeying.api.invitation.GenerateResponse>}
 */
const methodDescriptor_Invitation_Generate = new grpc.web.MethodDescriptor(
  '/yeying.api.invitation.Invitation/Generate',
  grpc.web.MethodType.UNARY,
  proto.yeying.api.invitation.GenerateRequest,
  proto.yeying.api.invitation.GenerateResponse,
  /**
   * @param {!proto.yeying.api.invitation.GenerateRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.yeying.api.invitation.GenerateResponse.deserializeBinary
);


/**
 * @param {!proto.yeying.api.invitation.GenerateRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.yeying.api.invitation.GenerateResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.yeying.api.invitation.GenerateResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.yeying.api.invitation.InvitationClient.prototype.generate =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/yeying.api.invitation.Invitation/Generate',
      request,
      metadata || {},
      methodDescriptor_Invitation_Generate,
      callback);
};


/**
 * @param {!proto.yeying.api.invitation.GenerateRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.yeying.api.invitation.GenerateResponse>}
 *     Promise that resolves to the response
 */
proto.yeying.api.invitation.InvitationPromiseClient.prototype.generate =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/yeying.api.invitation.Invitation/Generate',
      request,
      metadata || {},
      methodDescriptor_Invitation_Generate);
};


module.exports = proto.yeying.api.invitation;

