/**
 * @fileoverview gRPC-Web generated client stub for yeying.api.asset
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v4.25.0
// source: yeying/api/asset/asset.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as yeying_api_asset_asset_pb from '../../../yeying/api/asset/asset_pb'; // proto import: "yeying/api/asset/asset.proto"


export class AssetClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSearch = new grpcWeb.MethodDescriptor(
    '/yeying.api.asset.Asset/Search',
    grpcWeb.MethodType.UNARY,
    yeying_api_asset_asset_pb.SearchRequest,
    yeying_api_asset_asset_pb.SearchResponse,
    (request: yeying_api_asset_asset_pb.SearchRequest) => {
      return request.serializeBinary();
    },
    yeying_api_asset_asset_pb.SearchResponse.deserializeBinary
  );

  search(
    request: yeying_api_asset_asset_pb.SearchRequest,
    metadata?: grpcWeb.Metadata | null): Promise<yeying_api_asset_asset_pb.SearchResponse>;

  search(
    request: yeying_api_asset_asset_pb.SearchRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: yeying_api_asset_asset_pb.SearchResponse) => void): grpcWeb.ClientReadableStream<yeying_api_asset_asset_pb.SearchResponse>;

  search(
    request: yeying_api_asset_asset_pb.SearchRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: yeying_api_asset_asset_pb.SearchResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/yeying.api.asset.Asset/Search',
        request,
        metadata || {},
        this.methodDescriptorSearch,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/yeying.api.asset.Asset/Search',
    request,
    metadata || {},
    this.methodDescriptorSearch);
  }

  methodDescriptorSign = new grpcWeb.MethodDescriptor(
    '/yeying.api.asset.Asset/Sign',
    grpcWeb.MethodType.UNARY,
    yeying_api_asset_asset_pb.SignRequest,
    yeying_api_asset_asset_pb.SignResponse,
    (request: yeying_api_asset_asset_pb.SignRequest) => {
      return request.serializeBinary();
    },
    yeying_api_asset_asset_pb.SignResponse.deserializeBinary
  );

  sign(
    request: yeying_api_asset_asset_pb.SignRequest,
    metadata?: grpcWeb.Metadata | null): Promise<yeying_api_asset_asset_pb.SignResponse>;

  sign(
    request: yeying_api_asset_asset_pb.SignRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: yeying_api_asset_asset_pb.SignResponse) => void): grpcWeb.ClientReadableStream<yeying_api_asset_asset_pb.SignResponse>;

  sign(
    request: yeying_api_asset_asset_pb.SignRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: yeying_api_asset_asset_pb.SignResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/yeying.api.asset.Asset/Sign',
        request,
        metadata || {},
        this.methodDescriptorSign,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/yeying.api.asset.Asset/Sign',
    request,
    metadata || {},
    this.methodDescriptorSign);
  }

  methodDescriptorVersion = new grpcWeb.MethodDescriptor(
    '/yeying.api.asset.Asset/Version',
    grpcWeb.MethodType.UNARY,
    yeying_api_asset_asset_pb.VersionRequest,
    yeying_api_asset_asset_pb.VersionResponse,
    (request: yeying_api_asset_asset_pb.VersionRequest) => {
      return request.serializeBinary();
    },
    yeying_api_asset_asset_pb.VersionResponse.deserializeBinary
  );

  version(
    request: yeying_api_asset_asset_pb.VersionRequest,
    metadata?: grpcWeb.Metadata | null): Promise<yeying_api_asset_asset_pb.VersionResponse>;

  version(
    request: yeying_api_asset_asset_pb.VersionRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: yeying_api_asset_asset_pb.VersionResponse) => void): grpcWeb.ClientReadableStream<yeying_api_asset_asset_pb.VersionResponse>;

  version(
    request: yeying_api_asset_asset_pb.VersionRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: yeying_api_asset_asset_pb.VersionResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/yeying.api.asset.Asset/Version',
        request,
        metadata || {},
        this.methodDescriptorVersion,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/yeying.api.asset.Asset/Version',
    request,
    metadata || {},
    this.methodDescriptorVersion);
  }

  methodDescriptorDetail = new grpcWeb.MethodDescriptor(
    '/yeying.api.asset.Asset/Detail',
    grpcWeb.MethodType.UNARY,
    yeying_api_asset_asset_pb.DetailRequest,
    yeying_api_asset_asset_pb.DetailResponse,
    (request: yeying_api_asset_asset_pb.DetailRequest) => {
      return request.serializeBinary();
    },
    yeying_api_asset_asset_pb.DetailResponse.deserializeBinary
  );

  detail(
    request: yeying_api_asset_asset_pb.DetailRequest,
    metadata?: grpcWeb.Metadata | null): Promise<yeying_api_asset_asset_pb.DetailResponse>;

  detail(
    request: yeying_api_asset_asset_pb.DetailRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: yeying_api_asset_asset_pb.DetailResponse) => void): grpcWeb.ClientReadableStream<yeying_api_asset_asset_pb.DetailResponse>;

  detail(
    request: yeying_api_asset_asset_pb.DetailRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: yeying_api_asset_asset_pb.DetailResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/yeying.api.asset.Asset/Detail',
        request,
        metadata || {},
        this.methodDescriptorDetail,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/yeying.api.asset.Asset/Detail',
    request,
    metadata || {},
    this.methodDescriptorDetail);
  }

  methodDescriptorRemove = new grpcWeb.MethodDescriptor(
    '/yeying.api.asset.Asset/Remove',
    grpcWeb.MethodType.UNARY,
    yeying_api_asset_asset_pb.RemoveRequest,
    yeying_api_asset_asset_pb.RemoveResponse,
    (request: yeying_api_asset_asset_pb.RemoveRequest) => {
      return request.serializeBinary();
    },
    yeying_api_asset_asset_pb.RemoveResponse.deserializeBinary
  );

  remove(
    request: yeying_api_asset_asset_pb.RemoveRequest,
    metadata?: grpcWeb.Metadata | null): Promise<yeying_api_asset_asset_pb.RemoveResponse>;

  remove(
    request: yeying_api_asset_asset_pb.RemoveRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: yeying_api_asset_asset_pb.RemoveResponse) => void): grpcWeb.ClientReadableStream<yeying_api_asset_asset_pb.RemoveResponse>;

  remove(
    request: yeying_api_asset_asset_pb.RemoveRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: yeying_api_asset_asset_pb.RemoveResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/yeying.api.asset.Asset/Remove',
        request,
        metadata || {},
        this.methodDescriptorRemove,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/yeying.api.asset.Asset/Remove',
    request,
    metadata || {},
    this.methodDescriptorRemove);
  }

  methodDescriptorPut = new grpcWeb.MethodDescriptor(
    '/yeying.api.asset.Asset/Put',
    grpcWeb.MethodType.UNARY,
    yeying_api_asset_asset_pb.PutRequest,
    yeying_api_asset_asset_pb.PutResponse,
    (request: yeying_api_asset_asset_pb.PutRequest) => {
      return request.serializeBinary();
    },
    yeying_api_asset_asset_pb.PutResponse.deserializeBinary
  );

  put(
    request: yeying_api_asset_asset_pb.PutRequest,
    metadata?: grpcWeb.Metadata | null): Promise<yeying_api_asset_asset_pb.PutResponse>;

  put(
    request: yeying_api_asset_asset_pb.PutRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: yeying_api_asset_asset_pb.PutResponse) => void): grpcWeb.ClientReadableStream<yeying_api_asset_asset_pb.PutResponse>;

  put(
    request: yeying_api_asset_asset_pb.PutRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: yeying_api_asset_asset_pb.PutResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/yeying.api.asset.Asset/Put',
        request,
        metadata || {},
        this.methodDescriptorPut,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/yeying.api.asset.Asset/Put',
    request,
    metadata || {},
    this.methodDescriptorPut);
  }

  methodDescriptorGet = new grpcWeb.MethodDescriptor(
    '/yeying.api.asset.Asset/Get',
    grpcWeb.MethodType.UNARY,
    yeying_api_asset_asset_pb.GetRequest,
    yeying_api_asset_asset_pb.GetResponse,
    (request: yeying_api_asset_asset_pb.GetRequest) => {
      return request.serializeBinary();
    },
    yeying_api_asset_asset_pb.GetResponse.deserializeBinary
  );

  get(
    request: yeying_api_asset_asset_pb.GetRequest,
    metadata?: grpcWeb.Metadata | null): Promise<yeying_api_asset_asset_pb.GetResponse>;

  get(
    request: yeying_api_asset_asset_pb.GetRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: yeying_api_asset_asset_pb.GetResponse) => void): grpcWeb.ClientReadableStream<yeying_api_asset_asset_pb.GetResponse>;

  get(
    request: yeying_api_asset_asset_pb.GetRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: yeying_api_asset_asset_pb.GetResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/yeying.api.asset.Asset/Get',
        request,
        metadata || {},
        this.methodDescriptorGet,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/yeying.api.asset.Asset/Get',
    request,
    metadata || {},
    this.methodDescriptorGet);
  }

  methodDescriptorStreamGet = new grpcWeb.MethodDescriptor(
    '/yeying.api.asset.Asset/StreamGet',
    grpcWeb.MethodType.SERVER_STREAMING,
    yeying_api_asset_asset_pb.GetRequest,
    yeying_api_asset_asset_pb.StreamGetResponse,
    (request: yeying_api_asset_asset_pb.GetRequest) => {
      return request.serializeBinary();
    },
    yeying_api_asset_asset_pb.StreamGetResponse.deserializeBinary
  );

  streamGet(
    request: yeying_api_asset_asset_pb.GetRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<yeying_api_asset_asset_pb.StreamGetResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/yeying.api.asset.Asset/StreamGet',
      request,
      metadata || {},
      this.methodDescriptorStreamGet);
  }

}

