/**
 * @fileoverview gRPC-Web generated client stub for yeying.api.support
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.2
// source: yeying/api/support/support.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as yeying_api_support_support_pb from '../../../yeying/api/support/support_pb'; // proto import: "yeying/api/support/support.proto"


export class SupportClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCollect = new grpcWeb.MethodDescriptor(
    '/yeying.api.support.Support/Collect',
    grpcWeb.MethodType.UNARY,
    yeying_api_support_support_pb.CollectRequest,
    yeying_api_support_support_pb.CollectResponse,
    (request: yeying_api_support_support_pb.CollectRequest) => {
      return request.serializeBinary();
    },
    yeying_api_support_support_pb.CollectResponse.deserializeBinary
  );

  collect(
    request: yeying_api_support_support_pb.CollectRequest,
    metadata?: grpcWeb.Metadata | null): Promise<yeying_api_support_support_pb.CollectResponse>;

  collect(
    request: yeying_api_support_support_pb.CollectRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: yeying_api_support_support_pb.CollectResponse) => void): grpcWeb.ClientReadableStream<yeying_api_support_support_pb.CollectResponse>;

  collect(
    request: yeying_api_support_support_pb.CollectRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: yeying_api_support_support_pb.CollectResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/yeying.api.support.Support/Collect',
        request,
        metadata || {},
        this.methodDescriptorCollect,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/yeying.api.support.Support/Collect',
    request,
    metadata || {},
    this.methodDescriptorCollect);
  }

}

